// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {detector} from '../models';
import {profile} from '../models';

export function Bootstrap():Promise<app.BootstrapResult>;

export function CancelJob(arg1:string,arg2:string):Promise<void>;

export function CleanupTempArtifacts(arg1:Array<string>):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DetectExternalTools():Promise<detector.DetectionResult>;

export function DuplicateProfile(arg1:string,arg2:string):Promise<profile.Profile>;

export function GetCommandPreview(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetGPUInfo():Promise<string>;

export function ListProfiles():Promise<Array<profile.Profile>>;

export function ListTempArtifacts():Promise<Array<string>>;

export function OpenDirectoryDialog():Promise<Array<string>>;

export function OpenFileDialog():Promise<Array<string>>;

export function RequestAbort(arg1:string):Promise<void>;

export function RequestGracefulStop(arg1:string):Promise<void>;

export function ResolveOverwrite(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveAppConfig(arg1:string):Promise<void>;

export function SetDefaultProfile(arg1:string):Promise<void>;

export function SkipJob(arg1:string,arg2:string):Promise<void>;

export function StartEncode(arg1:string):Promise<void>;

export function UpsertProfile(arg1:string):Promise<void>;
