// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Bootstrap() {
  return window['go']['app']['App']['Bootstrap']();
}

export function CancelJob(arg1, arg2) {
  return window['go']['app']['App']['CancelJob'](arg1, arg2);
}

export function CleanupTempArtifacts(arg1) {
  return window['go']['app']['App']['CleanupTempArtifacts'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['app']['App']['DeleteProfile'](arg1);
}

export function DetectExternalTools() {
  return window['go']['app']['App']['DetectExternalTools']();
}

export function DuplicateProfile(arg1, arg2) {
  return window['go']['app']['App']['DuplicateProfile'](arg1, arg2);
}

export function GetCommandPreview(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetCommandPreview'](arg1, arg2, arg3);
}

export function GetGPUInfo() {
  return window['go']['app']['App']['GetGPUInfo']();
}

export function ListProfiles() {
  return window['go']['app']['App']['ListProfiles']();
}

export function ListTempArtifacts() {
  return window['go']['app']['App']['ListTempArtifacts']();
}

export function OpenDirectoryDialog() {
  return window['go']['app']['App']['OpenDirectoryDialog']();
}

export function OpenFileDialog() {
  return window['go']['app']['App']['OpenFileDialog']();
}

export function RequestAbort(arg1) {
  return window['go']['app']['App']['RequestAbort'](arg1);
}

export function RequestGracefulStop(arg1) {
  return window['go']['app']['App']['RequestGracefulStop'](arg1);
}

export function ResolveOverwrite(arg1, arg2, arg3) {
  return window['go']['app']['App']['ResolveOverwrite'](arg1, arg2, arg3);
}

export function SaveAppConfig(arg1) {
  return window['go']['app']['App']['SaveAppConfig'](arg1);
}

export function SetDefaultProfile(arg1) {
  return window['go']['app']['App']['SetDefaultProfile'](arg1);
}

export function SkipJob(arg1, arg2) {
  return window['go']['app']['App']['SkipJob'](arg1, arg2);
}

export function StartEncode(arg1) {
  return window['go']['app']['App']['StartEncode'](arg1);
}

export function UpsertProfile(arg1) {
  return window['go']['app']['App']['UpsertProfile'](arg1);
}
