// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Bootstrap() {
  return window['go']['main']['App']['Bootstrap']();
}

export function CancelJob(arg1, arg2) {
  return window['go']['main']['App']['CancelJob'](arg1, arg2);
}

export function CleanupTempArtifacts(arg1) {
  return window['go']['main']['App']['CleanupTempArtifacts'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DetectExternalTools() {
  return window['go']['main']['App']['DetectExternalTools']();
}

export function DuplicateProfile(arg1, arg2) {
  return window['go']['main']['App']['DuplicateProfile'](arg1, arg2);
}

export function GetGPUInfo() {
  return window['go']['main']['App']['GetGPUInfo']();
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function ListTempArtifacts() {
  return window['go']['main']['App']['ListTempArtifacts']();
}

export function PreviewCommand(arg1) {
  return window['go']['main']['App']['PreviewCommand'](arg1);
}

export function RequestAbort(arg1) {
  return window['go']['main']['App']['RequestAbort'](arg1);
}

export function RequestGracefulStop(arg1) {
  return window['go']['main']['App']['RequestGracefulStop'](arg1);
}

export function ResolveOverwrite(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResolveOverwrite'](arg1, arg2, arg3);
}

export function SaveAppConfig(arg1) {
  return window['go']['main']['App']['SaveAppConfig'](arg1);
}

export function SetDefaultProfile(arg1) {
  return window['go']['main']['App']['SetDefaultProfile'](arg1);
}

export function StartEncode(arg1) {
  return window['go']['main']['App']['StartEncode'](arg1);
}

export function UpsertProfile(arg1) {
  return window['go']['main']['App']['UpsertProfile'](arg1);
}
