// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function Bootstrap():Promise<model.BootstrapResponse>;

export function CancelJob(arg1:string,arg2:string):Promise<void>;

export function CleanupTempArtifacts(arg1:Array<string>):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DetectExternalTools():Promise<model.ToolSnapshot>;

export function DuplicateProfile(arg1:string,arg2:string):Promise<model.Profile>;

export function GetGPUInfo():Promise<model.GPUInfo>;

export function ListProfiles():Promise<Array<model.Profile>>;

export function ListTempArtifacts():Promise<Array<string>>;

export function PreviewCommand(arg1:model.PreviewCommandRequest):Promise<model.PreviewCommandResponse>;

export function RequestAbort(arg1:string):Promise<void>;

export function RequestGracefulStop(arg1:string):Promise<void>;

export function ResolveOverwrite(arg1:string,arg2:string,arg3:model.ResolveOverwriteDecision):Promise<void>;

export function SaveAppConfig(arg1:model.AppConfig):Promise<void>;

export function SetDefaultProfile(arg1:string):Promise<void>;

export function StartEncode(arg1:model.StartEncodeRequest):Promise<model.EncodeSession>;

export function UpsertProfile(arg1:model.Profile):Promise<model.Profile>;
